name: Push to GitHub Container Registry

on:
  push:
    branches:
      - main

env:
  redirect_uri: ${{ vars.REDIRECT_URI }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo 'envs Set REDIRECT_URI to $redirect_uri'
      - run: echo 'vars Set REDIRECT_URI to ${{ vars.REDIRECT_URI }}'
      - run: echo 'Did this shit works?'
      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.server
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/ninjacats/server:${{ github.sha }}
        env:
          REDIRECT_URI: ${{ vars.REDIRECT_URI }}